# Site settings
title: xiexianbin's blog
email: me@xiexianbin.cn
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.xiexianbin.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  xiexianbin

# Build settings
# markdown: kramdown
paginate: 5
paginate_path: "page:num"
# url链接格式
permalink: /:year/:month/:day/:title
#代码高亮
highlighter: pygments
mardown: redcarpet